#pragma once

// SDCARD
#define SDCARD_SCK_PIN 12
#define SDCARD_MISO_PIN 27
#define SDCARD_MOSI_PIN 14
#define SDCARD_CS_PIN 21

// SENSOR
#define FLOWSENSOR_OUT_PIN 25
#define FLOWSENSOR_IN_PIN 32
#define LOADCELL_1_PIN 36
#define LOADCELL_2_PIN 39
#define LOADCELL_3_PIN 34
#define LOADCELL_4_PIN 35

// ACTUATORS
#define PUMP_OUT_PIN 26
#define PUMP_IN_PIN 33